wandb_version: 1

activation_func:
  desc: null
  value: sigmoid
hidden_layers:
  desc: null
  value:
  - 6
  - 6
lr:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: mini-batch
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697403244.081506
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.4
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
